apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
        - name: orders-db
          image: centos/mongodb-34-centos7
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-creds
                  key: mongodb_user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-creds
                  key: mongodb_password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-creds
                  key: mongodb_database
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-creds
                  key: mongodb_admin_password
          ports:
            - name: mongo
              containerPort: 27017
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: /tmp
              name: orders-db-temp-vol
            - mountPath: /var/lib/mongodb/data
              name: orders-db-vol
      volumes:
        - name: orders-db-temp-vol
          emptyDir:
            medium: Memory
        - name: orders-db-vol
          emptyDir:
            medium: Memory