# =============================================================================
# Monitoring — dev 环境覆盖
# =============================================================================

namespace: monitoring-dev

ingress:
  enabled: true
  className: nginx
  prometheusHost: sockshop-dev.prometheus.lukas.cloud-ip.cc    # <-- 留空，用户自行填写
  grafanaHost: sockshop-dev.grafana.lukas.cloud-ip.cc      # <-- 留空，用户自行填写
  tls:
    enabled: false
    secretName: ""

prometheus:
  replicas: 1
  retention: 3d

grafana:
  replicas: 1

nodeExporter:
  enabled: true
