apiVersion: v1
kind: Secret
metadata:
  name: catalogue-db-secret
  namespace: {{ include "sock-shop.namespace" . }}
  labels:
    {{- include "sock-shop.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.catalogueDbPassword | b64enc | quote }}
